# Cấu hình Cloudflare Pages + D1
name = "guiyeuthuong"
pages_build_output_dir = "public"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "guiyeuthuong-db"
# Cơ sở dữ liệu trên Cloudflare (tạo ngày 01/10/2026)
database_id = "365014b9-649b-4a38-a7b0-36dad9823ca7"
migrations_dir = "migrations"
